version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.test
    env_file:
      - .env
    container_name: backend
    expose:
      - "8000"
    depends_on:
      - db
      - redis

  frontend:
    build: 
        context: ./frontend
        dockerfile: Dockerfile.test
    env_file:
      - .env
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/test.conf:/etc/nginx/conf.d/default.conf
      - ./backend/static:/app/static
      - ./backend/media:/app/media
    depends_on:
      - backend
      - frontend

  db:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
  
  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    command: celery -A photomap worker -l info
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - redis
    env_file:
      - .env 

volumes:
  pgdata:
