version: '3.8'

services:
  backend:
    build: ./backend
    env_file:
      - .env
    container_name: backend
    expose:
      - "8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend
    expose:
      - "3000"
    depends_on:
      - backend

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend/static:/app/static
      - ./backend/media:/app/media
    depends_on:
      - backend
      - frontend

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
